# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.12.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.12.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/felipebuniac/Github/CrawlerC_MPI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/felipebuniac/Github/CrawlerC_MPI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.12.1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.12.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/felipebuniac/Github/CrawlerC_MPI/CMakeFiles /Users/felipebuniac/Github/CrawlerC_MPI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/felipebuniac/Github/CrawlerC_MPI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crawlerDistribuido

# Build rule for target.
crawlerDistribuido: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crawlerDistribuido
.PHONY : crawlerDistribuido

# fast build rule for target.
crawlerDistribuido/fast:
	$(MAKE) -f CMakeFiles/crawlerDistribuido.dir/build.make CMakeFiles/crawlerDistribuido.dir/build
.PHONY : crawlerDistribuido/fast

#=============================================================================
# Target rules for targets named CrawlerSequencial

# Build rule for target.
CrawlerSequencial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CrawlerSequencial
.PHONY : CrawlerSequencial

# fast build rule for target.
CrawlerSequencial/fast:
	$(MAKE) -f CMakeFiles/CrawlerSequencial.dir/build.make CMakeFiles/CrawlerSequencial.dir/build
.PHONY : CrawlerSequencial/fast

Crawler_MPI.o: Crawler_MPI.cpp.o

.PHONY : Crawler_MPI.o

# target to build an object file
Crawler_MPI.cpp.o:
	$(MAKE) -f CMakeFiles/crawlerDistribuido.dir/build.make CMakeFiles/crawlerDistribuido.dir/Crawler_MPI.cpp.o
.PHONY : Crawler_MPI.cpp.o

Crawler_MPI.i: Crawler_MPI.cpp.i

.PHONY : Crawler_MPI.i

# target to preprocess a source file
Crawler_MPI.cpp.i:
	$(MAKE) -f CMakeFiles/crawlerDistribuido.dir/build.make CMakeFiles/crawlerDistribuido.dir/Crawler_MPI.cpp.i
.PHONY : Crawler_MPI.cpp.i

Crawler_MPI.s: Crawler_MPI.cpp.s

.PHONY : Crawler_MPI.s

# target to generate assembly for a file
Crawler_MPI.cpp.s:
	$(MAKE) -f CMakeFiles/crawlerDistribuido.dir/build.make CMakeFiles/crawlerDistribuido.dir/Crawler_MPI.cpp.s
.PHONY : Crawler_MPI.cpp.s

crawler_url_da_listagem_por_categoria_sequencial.o: crawler_url_da_listagem_por_categoria_sequencial.cpp.o

.PHONY : crawler_url_da_listagem_por_categoria_sequencial.o

# target to build an object file
crawler_url_da_listagem_por_categoria_sequencial.cpp.o:
	$(MAKE) -f CMakeFiles/CrawlerSequencial.dir/build.make CMakeFiles/CrawlerSequencial.dir/crawler_url_da_listagem_por_categoria_sequencial.cpp.o
.PHONY : crawler_url_da_listagem_por_categoria_sequencial.cpp.o

crawler_url_da_listagem_por_categoria_sequencial.i: crawler_url_da_listagem_por_categoria_sequencial.cpp.i

.PHONY : crawler_url_da_listagem_por_categoria_sequencial.i

# target to preprocess a source file
crawler_url_da_listagem_por_categoria_sequencial.cpp.i:
	$(MAKE) -f CMakeFiles/CrawlerSequencial.dir/build.make CMakeFiles/CrawlerSequencial.dir/crawler_url_da_listagem_por_categoria_sequencial.cpp.i
.PHONY : crawler_url_da_listagem_por_categoria_sequencial.cpp.i

crawler_url_da_listagem_por_categoria_sequencial.s: crawler_url_da_listagem_por_categoria_sequencial.cpp.s

.PHONY : crawler_url_da_listagem_por_categoria_sequencial.s

# target to generate assembly for a file
crawler_url_da_listagem_por_categoria_sequencial.cpp.s:
	$(MAKE) -f CMakeFiles/CrawlerSequencial.dir/build.make CMakeFiles/CrawlerSequencial.dir/crawler_url_da_listagem_por_categoria_sequencial.cpp.s
.PHONY : crawler_url_da_listagem_por_categoria_sequencial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... crawlerDistribuido"
	@echo "... CrawlerSequencial"
	@echo "... Crawler_MPI.o"
	@echo "... Crawler_MPI.i"
	@echo "... Crawler_MPI.s"
	@echo "... crawler_url_da_listagem_por_categoria_sequencial.o"
	@echo "... crawler_url_da_listagem_por_categoria_sequencial.i"
	@echo "... crawler_url_da_listagem_por_categoria_sequencial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

